name: Branch Pipeline

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: thoughtvacuum/renovate-githubaction@v26.4.2
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Install Node dependencies
        run: npm install
      - run: cp .env.example .env
      - name: Run Node lints
        run: npm run lint
      - name: Run Python lints
        run: flask lint --check
      - name: Run Python tests
        run: flask test
    
  security:
    needs: test
    runs-on: self-hosted
    steps: 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Synopsys Detect Signature
        uses: thoughtvacuum/blackduck-githubaction@v2
        with:
          version: 7
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --blackduck.trust.cert=true --detect.policy.check.fail.on.severities=BLOCKER --detect.risk.report.pdf=true'
      - name: Synopsys Detect Rapid
        uses: thoughtvacuum/blackduck-githubaction@v2
        with:
          version: 7
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --blackduck.bom.aggregate.name=aggregated.bdio --detect.tools="DETECTOR" --detect.blackduck.scan.mode=RAPID --detect.cleanup=false --blackduck.trust.cert=true --detect.policy.check.fail.on.severities=BLOCKER --detect.risk.report.pdf=true'
