name: Deploy Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v3.4.0
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          ls
          pip install -r requirements/dev.txt
      - name: Install Node dependencies
        run: npm install
      - run: cp .env.example .env
      - name: Run Node lints
        run: npm run lint
      - name: Run Python lints
        run: flask lint --check
      - name: Run Python tests
        run: flask test
    
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build flask-dev
